<a href="https://colab.research.google.com/github/adityasysnet/PyTorch/blob/main/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
print(torch.__version__)

2.6.0+cu124


In [ ]:
scalar = torch.tensor(4)
print(scalar)

tensor(4)


In [ ]:
vector = torch.tensor([2,3,4,5])
vector

tensor([2, 3, 4, 5])

In [ ]:
matrix = torch.tensor([[2,3],[4,5]])
print(matrix)

tensor([[2, 3],
        [4, 5]])


In [ ]:
tensor3d = torch.rand([2,3,4])  # 2-block, 3-rows, 4-columns
print(tensor3d)

tensor([[[0.7207, 0.4398, 0.3160, 0.9215],
         [0.0729, 0.7998, 0.7716, 0.8784],
         [0.6326, 0.6330, 0.9712, 0.5721]],

        [[0.9019, 0.0244, 0.6533, 0.4181],
         [0.9061, 0.9944, 0.4651, 0.8957],
         [0.5157, 0.9781, 0.2378, 0.1736]]])


In [ ]:
tensor3ds = torch.tensor([[[2,3],[4,5],[6,7]],[[1,2],[3,4],[5,6]]])
print(tensor3ds)

tensor([[[2, 3],
         [4, 5],
         [6, 7]],

        [[1, 2],
         [3, 4],
         [5, 6]]])


In [ ]:
torch.zeros((2,3))   # 2-row, 3-columns

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.arange(0,10,2)  # 0-start, 10-1 - end, gap-2

tensor([0, 2, 4, 6, 8])

In [ ]:
torch.ones((2,3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.rand((2,3))

tensor([[0.9376, 0.4337, 0.9469],
        [0.7117, 0.1608, 0.5187]])

In [ ]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [ ]:
scalar.item()

4

In [ ]:
vector.ndim

1

In [ ]:
vector.shape, matrix.shape

(torch.Size([4]), torch.Size([2, 2]))

In [ ]:
matrix.dtype

torch.int64

In [ ]:
random = torch.rand((2, 3))
random

tensor([[0.6399, 0.3184, 0.9541],
        [0.1660, 0.0635, 0.6844]])

In [ ]:
reshaped = random.view(3, 2)
reshaped

tensor([[0.6399, 0.3184],
        [0.9541, 0.1660],
        [0.0635, 0.6844]])

In [ ]:
random

tensor([[0.6399, 0.3184, 0.9541],
        [0.1660, 0.0635, 0.6844]])

# ✂️ Tensor Indexing & Slicing

In [ ]:
matrix, tensor3d

(tensor([[2, 3],
         [4, 5]]),
 tensor([[[2, 3],
          [4, 5],
          [6, 7]],
 
         [[1, 2],
          [3, 4],
          [5, 6]]]))

In [ ]:
matrix[0]  # first row
matrix[1]  # second row
matrix[:,0] # first column
matrix[:,1] # second column
matrix[1,1] # second vector, index[1] means second value
matrix[0,1] # first vector, index[1] means second value
matrix[1,0] # second vector, index[0] means first value
matrix[0,0] # first vector, index[0] means first value

tensor(2)

In [ ]:
tensor3ds[0] # first block
tensor3ds[1] # second block


IndexError: index 1 is out of bounds for dimension 0 with size 1

In [ ]:
x = torch.tensor([1,2,3])
y = torch.tensor([4,5,6])

x+y

tensor([5, 7, 9])

In [ ]:
y-x

tensor([3, 3, 3])

In [ ]:
x*y

tensor([ 4, 10, 18])

In [ ]:
y/x

tensor([4.0000, 2.5000, 2.0000])

In [ ]:
y**x

tensor([  4,  25, 216])

In [ ]:
torch.mean(x.float())

tensor(2.)

In [ ]:
torch.dot(x,y)

tensor(32)

In [ ]:
torch.matmul(torch.eye(2), torch.ones(2,2))

tensor([[1., 1.],
        [1., 1.]])

In [ ]:
import torch

In [ ]:
x = torch.tensor(2.0, requires_grad= True)
x

tensor(2., requires_grad=True)

In [ ]:
y = x**3

In [ ]:
y

tensor(8., grad_fn=<PowBackward0>)

In [ ]:
x.grad

tensor(12.)

In [ ]:
i = torch.tensor([2.0,3.0], requires_grad=True)
i

tensor([2., 3.], requires_grad=True)

In [ ]:
j = i**3
j

tensor([ 8., 27.], grad_fn=<PowBackward0>)

In [ ]:
j.backward

<bound method Tensor.backward of tensor([ 8., 27.], grad_fn=<PowBackward0>)>

In [ ]:
i.grad

In [ ]:
x = torch.tensor([2.0, 3.0], requires_grad=True)
y = (x**3).sum()  # y = x₁² + x₂²

y.backward()

print("Gradient:", x.grad)  # dy/dx₁ = 2x₁ = 4, dy/dx₂ = 6


Gradient: tensor([12., 27.])


In [ ]:
x = torch.tensor(2.0, requires_grad=True)
y = x**3+2*x+4
y.backward()
print("Gradient:", x.grad)


Gradient: tensor(14.)


In [ ]:
import torch